dags:
  - dag_id: "cci_voyage_tMeta"
    table_name: "tMeta"
    query: "SELECT * FROM [Voyage].[dbo].[tMeta]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tmeta"

  - dag_id: "cci_voyage_tcust"
    table_name: "tCust"
    query: "SELECT * FROM [Voyage].[dbo].[tCust]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tcust"

  - dag_id: "cci_voyage_tInv"
    table_name: "tInv"
    query: "SELECT * FROM [Voyage].[dbo].[tInv]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tinv"

  - dag_id: "cci_voyage_tInvExtra"
    table_name: "tInvExtra"
    query: "SELECT * FROM [Voyage].[dbo].[tInvExtra]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tinvextra"

  - dag_id: "cci_voyage_tInvItem"
    table_name: "tInvItem"
    query: "SELECT * FROM [Voyage].[dbo].[tInvItem]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tinvitem"

  - dag_id: "cci_voyage_tCustProp"
    table_name: "tCustProp"
    query: "SELECT * FROM [Voyage].[dbo].[tCustProp]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tcustprop"

  - dag_id: "cci_voyage_tCustDist"
    table_name: "tCustDist"
    query: "SELECT * FROM [Voyage].[dbo].[tCustDist]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tcustdist"

  - dag_id: "cci_voyage_tCity"
    table_name: "tCity"
    query: "SELECT * FROM [Voyage].[dbo].[tCity]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tcity"

  - dag_id: "cci_voyage_tSeller"
    table_name: "tSeller"
    query: "SELECT * FROM [Voyage].[dbo].[tSeller]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tseller"

  - dag_id: "cci_voyage_tTown"
    table_name: "tTown"
    query: "SELECT * FROM [Voyage].[dbo].[tTown]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "ttown"

  - dag_id: "cci_voyage_tDeliverer"
    table_name: "tDeliverer"
    query: "SELECT * FROM [Voyage].[dbo].[tDeliverer]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tdeliverer"

  - dag_id: "cci_voyage_tDist"
    table_name: "tDist"
    query: "SELECT * FROM [Voyage].[dbo].[tDist]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tdist"

  - dag_id: "cci_voyage_tLoyaltyParticipant"
    table_name: "tLoyaltyParticipant"
    query: "SELECT * FROM [Voyage].[dbo].[tLoyaltyParticipant]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tloyaltyparticipant"
  
  - dag_id: "cci_voyage_tPropDef"
    table_name: "tPropDef"
    query: "SELECT * FROM [Voyage].[dbo].[tPropDef]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tpropdef"

  - dag_id: "cci_voyage_tPropInfo"
    table_name: "tPropInfo"
    query: "SELECT * FROM [Voyage].[dbo].[tPropInfo]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tpropinfo"

  - dag_id: "cci_voyage_tSellerType"
    table_name: "tSellerType"
    query: "SELECT * FROM [Voyage].[dbo].[tSellerType]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tsellertype"

  - dag_id: "cci_voyage_tUser"
    table_name: "tUser"
    query: "SELECT * FROM [Voyage].[dbo].[tUser]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tuser"
  
  - dag_id: "cci_voyage_tDelivery"
    table_name: "tDelivery"
    query: "SELECT * FROM [Voyage].[dbo].[tDelivery]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tdelivery"

  - dag_id: "cci_voyage_tMYA"
    table_name: "tMYA"
    query: "SELECT * FROM [Voyage].[dbo].[tMYA]"
    gcs_bucket: "cci_staging_data"
    gbq_dataset: "cci_staging_data"
    gbq_table: "tmya"

